export enum PermissionKey {
    USER_REGISTER = "USER_REGISTER",
    USER_LOGIN = "USER_LOGIN",
    USER_UPDATE_OWN_PROFILE = "USER_UPDATE_OWN_PROFILE",
    USER_VIEW_OWN_PROFILE = "USER_VIEW_OWN_PROFILE",
    USER_ENABLE_2FA = "USER_ENABLE_2FA",
    USER_DISABLE_2FA = "USER_DISABLE_2FA",
    USER_MANAGE_SESSIONS = "USER_MANAGE_SESSIONS",
    ADMIN_VIEW_USERS = "ADMIN_VIEW_USERS",
    ADMIN_CREATE_USERS = "ADMIN_CREATE_USERS",
    ADMIN_ACTIVATE_USER = "ADMIN_ACTIVATE_USER",
    ADMIN_DEACTIVATE_USER = "ADMIN_DEACTIVATE_USER",
    ADMIN_DELETE_USER = "ADMIN_DELETE_USER",
    ADMIN_VIEW_AUDIT_LOGS = "ADMIN_VIEW_AUDIT_LOGS",
    ADMIN_VIEW_SECURITY_LOGS = "ADMIN_VIEW_SECURITY_LOGS",
    ADMIN_EXPORT_AUDIT_LOGS = "ADMIN_EXPORT_AUDIT_LOGS",
    ADMIN_FORCE_PASSWORD_RESET = "ADMIN_FORCE_PASSWORD_RESET",
    ADMIN_MANAGE_ROLES = "ADMIN_MANAGE_ROLES",
    ADMIN_ASSIGN_ROLE_TO_USER = "ADMIN_ASSIGN_ROLE_TO_USER",
    ADMIN_MANAGE_REFERENCE_DATA = "ADMIN_MANAGE_REFERENCE_DATA",

    // =========================================
    // Gestion des Départements / Structure
    // =========================================
    MANAGE_DEPARTMENTS = "MANAGE_DEPARTMENTS",
    VIEW_DEPARTMENTS = "VIEW_DEPARTMENTS",

    // =========================================
    // Étudiants
    // =========================================
    STUDENT_VIEW_OWN_COURSES = "STUDENT_VIEW_OWN_COURSES",
    STUDENT_SUBMIT_ASSIGNMENTS = "STUDENT_SUBMIT_ASSIGNMENTS",
    STUDENT_VIEW_OWN_GRADES = "STUDENT_VIEW_OWN_GRADES",
    STUDENT_VIEW_SCHEDULE = "STUDENT_VIEW_SCHEDULE",
    STUDENT_VIEW_ANNOUNCEMENTS = "STUDENT_VIEW_ANNOUNCEMENTS",

    // =========================================
    // Staff / Formateurs
    // =========================================
    STAFF_MANAGE_OWN_COURSES = "STAFF_MANAGE_OWN_COURSES",
    STAFF_GRADE_STUDENTS = "STAFF_GRADE_STUDENTS",
    STAFF_VIEW_STUDENT_LIST = "STAFF_VIEW_STUDENT_LIST",
    STAFF_POST_ANNOUNCEMENTS = "STAFF_POST_ANNOUNCEMENTS",
    STAFF_VIEW_SCHEDULE = "STAFF_VIEW_SCHEDULE",

    // =========================================
    // Manager
    // =========================================
    MANAGER_VIEW_ALL_USERS = "MANAGER_VIEW_ALL_USERS",
    MANAGER_VIEW_REPORTS = "MANAGER_VIEW_REPORTS",
    MANAGER_MANAGE_STAFF = "MANAGER_MANAGE_STAFF",
    MANAGER_MANAGE_STUDENTS = "MANAGER_MANAGE_STUDENTS",
    MANAGER_MANAGE_SCHEDULES = "MANAGER_MANAGE_SCHEDULES",
    MANAGER_MANAGE_COURSES = "MANAGER_MANAGE_COURSES",
    MANAGER_VIEW_AUDIT_LOGS = "MANAGER_VIEW_AUDIT_LOGS",

    // =========================================
    // Secrétariat
    // =========================================
    SECRETARY_MANAGE_ENROLLMENTS = "SECRETARY_MANAGE_ENROLLMENTS",
    SECRETARY_VIEW_STUDENTS = "SECRETARY_VIEW_STUDENTS",
    SECRETARY_MANAGE_DOCUMENTS = "SECRETARY_MANAGE_DOCUMENTS",
    SECRETARY_SEND_NOTIFICATIONS = "SECRETARY_SEND_NOTIFICATIONS",
    SECRETARY_VIEW_SCHEDULE = "SECRETARY_VIEW_SCHEDULE",
    SECRETARY_MANAGE_SCHEDULE = "SECRETARY_MANAGE_SCHEDULE",

}